**用eval(),np.safe_eval()函数来从字符串转list，再转np.array**

**用eval(),np.safe_eval()函数来从字符串转list，再转np.array**

**用eval(),np.safe_eval()函数来从字符串转list，再转np.array**

In [23]:
# T061,s7-1
import numpy as np
s = input()
arr = np.array(s[1:len(s)-1].split(','), dtype=int)
mean = np.average(arr)
arr = np.compress(arr > mean, arr)
arr = np.tile(arr, (arr.size, 1))
print(arr)


[[7 9]
 [7 9]]


In [3]:
# T062,s7-2
import numpy as np
x = np.array(np.safe_eval(input()))
y = np.array(np.safe_eval(input()))
p = np.array(np.safe_eval(input()))
ans = []
for i in range(3):
    p1 = x[i]
    p2 = y[i]
    # 公式|a*x0+b*y0+c|/srqt(a**2+b**2)
    # a=y2-y1,b=x1-x2,c=x1*(y1-y2)+y1*(x2-x1)
    A = p2[1]-p1[1]
    B = p1[0]-p2[0]
    C = p1[0]*(p1[1]-p2[1])+p1[1]*(p2[0]-p1[0])
    distance = np.abs(A*p[0]+B*p[1]+C)/np.sqrt(A**2+B**2)
    ans.append(distance)
print(np.array(ans))


[0.4472136  0.83205029 1.26491106]


In [1]:
# T063,s7-3
import numpy as np
m = np.array(np.safe_eval(input()))
# print(m)
mu = np.mean(m)
sigma = np.std(m, ddof=0)
m = (m-mu)/sigma
m = np.round(m, decimals=8)
print(m)


[[-1.28864515 -0.45208796  0.11233629]
 [-0.14378263  0.77002098  1.44712055]
 [ 0.83619492 -1.84364199  0.56248499]]


In [24]:
# T064,s7-4
#题目说明不够清晰，如果两个数组差距为2怎么办呢？
import numpy as np
arr = np.array(np.safe_eval(input()))
ta = np.max(arr)
ti = np.min(arr)
arrNoMax = np.compress(arr < ta, arr)
arrNoMin = np.compress(arr > ti, arr)
print(list(arrNoMax))
print(list(arrNoMin))
if(arrNoMin.size < arrNoMax.size):
    for i in range(arrNoMax.size-arrNoMin.size):
        arrNoMin = np.append(arrNoMin, -1)
else:
    for i in range(arrNoMin.size-arrNoMax.size):
        arrNoMax = np.append(arrNoMax, -1)
# print(list(arrNoMax))
# print(list(arrNoMin))
arr = np.vstack((arrNoMax, arrNoMin))
print(arr)


[8, 1, 7, 1, 0, 5, 1, 0, 4]
[8, 9, 1, 7, 1, 5, 1, 4]
[8, 1, 7, 1, 0, 5, 1, 0, 4]
[8, 9, 1, 7, 1, 5, 1, 4, -1]
[[ 8  1  7  1  0  5  1  0  4]
 [ 8  9  1  7  1  5  1  4 -1]]


In [5]:
# T065,s7-5
# 如果是只做整数部分处理意义不明
import numpy as np
arr = np.array(np.safe_eval(input()))
arr = np.floor(arr)
dif = np.array(np.safe_eval(input()))
arr = np.setdiff1d(arr, dif)
ans = np.abs(arr-np.mean(arr)).argmin()
ans


0

In [18]:
# T066,s7-6
# 输出应该是(n+3)*(n+3)
import numpy as np
n = int(input())
m = np.zeros([n+3, n+3], int)
m[0] = -1
m[-1] = -1
m[:, 0] = -1
m[:, -1] = -1
for i in range(2, n+2):
    m[i, i-1] = i
m


array([[-1, -1, -1, -1, -1, -1, -1],
       [-1,  0,  0,  0,  0,  0, -1],
       [-1,  2,  0,  0,  0,  0, -1],
       [-1,  0,  3,  0,  0,  0, -1],
       [-1,  0,  0,  4,  0,  0, -1],
       [-1,  0,  0,  0,  5,  0, -1],
       [-1, -1, -1, -1, -1, -1, -1]])

In [122]:
# T067,s7-7
# 还是没有找到一个便捷的方法，用numpy求笛卡尔积
import numpy as np
import itertools
# ([1, 2, 3], [4, 5,6], [7,8,9])
s = eval(input())
print(np.array(list(itertools.product(s[0], s[1],s[2]))))


[[1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [1 6 7]
 [1 6 8]
 [1 6 9]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [2 6 7]
 [2 6 8]
 [2 6 9]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [3 5 7]
 [3 5 8]
 [3 5 9]
 [3 6 7]
 [3 6 8]
 [3 6 9]]


In [140]:
# T068,s7-8
import numpy as np
n = int(input())
ans = np.array([],dtype=int)
for i in range(n+1):
    ans = np.concatenate((ans, np.arange(i, i+n)))
print(ans.reshape(-1,n))

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]
 [5 6 7 8 9]]


In [136]:
# T069,s7-9
import numpy as np
c = int(input())
m = int(input())
n = int(input())
arr = np.array(eval(input()), dtype=int)
if c:
    arr[:, [m, n]] = arr[:, [n, m]]
else:
    arr[[m, n], :] = arr[[n, m], :]
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [12 13 14 15]
 [ 8  9 10 11]]


In [138]:
# T070,s7-10
import numpy as np
print(np.fromiter([x for x in range(5)], int))

[0 1 2 3 4]
