In [ ]:
str = ['ab', 'abc', 'addddddd']
z = zip(*str)
c =list(z)
print(c)

res = ""
for tmp in zip(*str):
    print(tmp)
    tmp_set = set(tmp)
    print(list(tmp_set))
    if len(tmp_set) == 1:
        res += tmp[0]
    else:
        break
print(res)

In [6]:
# s1-8
c1 = complex(input())
c2 = complex(input())
s = c1+c2
diff = c1 - c2
mul = c1*c2
quo = 'ERROR' if (c2 == 0) else c1/c2
conj = c1.conjugate()
absc = abs(c1)
print("{},{},{},{},{},{}".format(s, diff, mul, quo, conj, absc))

1+1j
1-1j
(2+0j),2j,(2+0j),1j,(1-1j),1.4142135623730951


In [11]:
# s1-9
n = int(input())
res = []
for i in range(n):
    m = bin(int(input()))[2:]
    print(m)
    if(all(t == '1' for t in m)):
        res.append(True)
    else:
        res.append(False)
print(','.join(str(i) for i in res))

2
15
1111
16
10000
True,False


In [2]:
print('b'>'a' and 'b'<'z')

True


In [1]:
print(ord('9')-ord('0'))
print('3'.isdigit())

9
True


In [1]:
li = [1, 2, 3]
print(*li)
print(' '.join(str(i) for i in li))
[*li]


1 2 3
1 2 3


[1, 2, 3]

In [19]:
[_ for _ in range(2, -1, -1)]


[2, 1, 0]

In [10]:
a = 0b1
bin(a<<1)
# bin(a)

'0b10'

In [ ]:
# 044,s5-4
class Stack:
    def __init__(self):
        self.stack = []

    def push(self, n):
        self.stack.append(n)

    def pop(self):
        if not self.stack:
            return
        self.stack.pop()

    def out(self):
        print(*self.stack)


s = Stack()
while(1):
    try:
        li = input()  # 现在是每一次的2后面都有空格，然后以eof为截止符
    except:
        break
    if '1' == li[0]:
        s.push(int(li[2:]))
    else:
        s.pop()
s.out()

In [59]:
# T061
s = input()
arr = list(map(int, s[1:len(s)-1].split(',')))
# print(arr)
mean = float(sum(arr))/len(arr)
arr = [i for i in arr if i > mean]
a = " ".join(str(i) for i in arr)
s = "[["
for i in range(len(arr)-1):
    s += a+"]\n"+" ["
    # s = "[["+a+"]\n"+" ["+a+"]\n"+" ["+a+"]]"
s += a+"]]"
print(s)


[[9 11 13]
 [9 11 13]
 [9 11 13]]


In [96]:
# numpy input
import numpy as np
s = input()
a=np.array(np.safe_eval(s),dtype=int)
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [2]:
import numpy as np

Z = np.array(eval(input()))
print(Z)
Z = (Z - np.mean(Z)) / (np.std(Z))
print(Z)


[[0.17551799 0.40883174 0.56624828]
 [0.49481734 0.74967493 0.93851634]
 [0.76813068 0.02073073 0.69179365]]
[[-1.28864515 -0.45208796  0.11233629]
 [-0.14378263  0.77002098  1.44712055]
 [ 0.83619492 -1.84364199  0.56248499]]


In [25]:
print("{:.3f}".format(1.1151))
print("%.2f" %(1.116))
print(round(1.1151,2))

1.115
1.12
1.12


In [18]:
# ndarray遍历

import numpy as np

a = np.array([[1,2], [2,3], [3,4]])
print(a)
for x in np.nditer(a):
    print(x,end=' ')
print(" ".join(str(x) for x in np.nditer(a)))

[[1 2]
 [2 3]
 [3 4]]
1 2 2 3 3 4 1 2 2 3 3 4


In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a[0,:])

[1 2 3]


In [30]:
from scipy.spatial.distance import cdist,pdist,squareform
import numpy as np
x1 =np.array([(0,0),(2,0),(10,0)])
print(cdist(x1,x1))
print(pdist(x1))
print(squareform(pdist(x1)))
print(cdist(x1,x1).sum(axis=0))
print(squareform(pdist(x1)).sum(axis=1).argmin())

[[ 0.  2. 10.]
 [ 2.  0.  8.]
 [10.  8.  0.]]
[ 2. 10.  8.]
[[ 0.  2. 10.]
 [ 2.  0.  8.]
 [10.  8.  0.]]
[12. 10. 18.]
1
